# Generated by Django 5.0.7 on 2024-07-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_ceo',
            field=models.BooleanField(default=False, verbose_name='CEO (first-in-command)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_dev',
            field=models.BooleanField(default=False, verbose_name='DEV (Developer)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_coo',
            field=models.BooleanField(default=False, verbose_name='COO (second-in-command)'),
        ),
    ]
