# Generated by Django 5.0.7 on 2024-07-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_userprofile_is_ceo_userprofile_is_dev_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_ceo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_dev',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_coo',
            field=models.BooleanField(default=False, verbose_name='COO (Director)'),
        ),
    ]
